import {chromium} from 'playwright';import assert from 'node:assert/strict';import {createServer} from '../server.mjs';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('screenshots',{recursive:true});const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});const results=[];
async function ready(scene,frame){await page.waitForFunction(([s,f])=>window.demo?.state.ready&&!window.demo.state.busy&&window.demo.state.scene.id===s&&window.demo.state.frame.key===f,[scene,frame],{timeout:60000});}
async function slider(id,v){await page.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(v));}
try{await page.goto(`http://127.0.0.1:${server.address().port}`);await ready('mic','F_001');assert.equal(await page.evaluate(()=>window.demo.renderer.getContext().isContextLost()),false);
 for(const scene of ['mic','materials']){await page.selectOption('#scene',scene);await ready(scene,'F_001');await page.click('#reset');await slider('percent',10);const count=await page.evaluate(()=>window.demo.state.selected.length),eligible=await page.evaluate(()=>window.demo.state.scene.eligible_count);assert.equal(count,Math.ceil(eligible*.1));await slider('percent',2);assert.ok(await page.evaluate(()=>window.demo.state.selected.length)<count);
 for(const method of ['baseline','enhanced'])for(const category of ['union','color','geometry','outline']){await page.selectOption('#method',method);await page.selectOption('#category',category);const ok=await page.evaluate(({method,category})=>{const s=window.demo.state,offset={union:0,color:2,geometry:4,outline:6}[category]+(method==='enhanced'?1:0),all=[];for(let i=0;i<s.scene.count;i++)if(s.scores[i*12+8]===1)all.push(i);all.sort((a,b)=>s.scores[b*12+offset]-s.scores[a*12+offset]||a-b);return JSON.stringify(s.selected)===JSON.stringify(all.slice(0,Math.ceil(all.length*.02)));},{method,category});assert.equal(ok,true);}await page.selectOption('#category','union');await slider('minScore',1);assert.ok(await page.evaluate(()=>window.demo.state.selected.length)<count);await slider('minScore',0);for(const overlay of ['oldA','oldB','oldC','evidence','none','selection'])await page.selectOption('#overlay',overlay);
 for(const frame of ['F_001','C_007','arc0_016']){await page.selectOption('#frame',frame);await ready(scene,frame);await page.click('#preset');await slider('minScore',0);await slider('evidenceCutoff',0);await slider('contributionCutoff',0);await slider('brushRadius',1);
 const p=await page.evaluate(()=>{const s=window.demo.state;for(let p=0;p<640000;p++)if(s.signals[p*7+3]>100&&s.weights[p*4]>.05)return {x:p%800,y:Math.floor(p/800)};throw Error('no evidence pixel')});const box=await page.locator('#imageCanvas').boundingBox();await page.mouse.click(box.x+(p.x+.5)/800*box.width,box.y+(p.y+.5)/800*box.height);
 const check=await page.evaluate(()=>{const d=window.demo,s=d.state,expected=d.core.brushSelection({...s,...d.settings});return {actual:s.selected,expected:expected.ids,pixels:s.pixels,unknown:s.selected.filter(i=>s.scores[i*12+9]===1).length};});assert.deepEqual(check.actual,check.expected);assert.ok(check.actual.length>0);assert.ok(check.pixels.length>0);
 await page.check('#lock');const locked=[...check.actual];const next=frame==='F_001'?'C_007':'F_001';await page.selectOption('#frame',next);await ready(scene,next);assert.deepEqual(await page.evaluate(()=>window.demo.state.selected),locked);assert.equal(await page.evaluate(()=>window.demo.state.pixels.length),0);await page.uncheck('#lock');await page.selectOption('#frame',frame);await ready(scene,frame);assert.equal(await page.evaluate(()=>window.demo.state.selected.length),0);
 results.push({scene,frame,selected_on_click:check.actual.length,unknown_selected:check.unknown});}
 await page.click('#reset');await slider('percent',10);await page.selectOption('#cap','5000');const exported=await page.evaluate(()=>window.demo.exportData());assert.equal(exported.original_ids.length,count);assert.ok(exported.original_ids.every(i=>i>=0&&i< (scene==='mic'?311562:282537)));assert.equal(new Set(exported.original_ids).size,count);const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;await download.saveAs(`screenshots/${scene}_export.json`);
 await page.click('#alignCamera');await page.screenshot({path:`screenshots/${scene}_global.png`,fullPage:true});
 await page.click('#preset');await slider('minScore',0);await slider('evidenceCutoff',0);await slider('percent',100);await page.selectOption('#tool','rectangle');const box=await page.locator('#imageCanvas').boundingBox();await page.mouse.move(box.x+box.width*.3,box.y+box.height*.3);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.65,{steps:8});await page.mouse.up();assert.ok(await page.evaluate(()=>window.demo.state.selected.length)>0);await slider('contributionCutoff',1);assert.equal(await page.evaluate(()=>window.demo.state.selected.length),0);await slider('contributionCutoff',.01);await slider('evidenceCutoff',1);const highEvidence=await page.evaluate(()=>window.demo.state.selected.length);await slider('evidenceCutoff',0);assert.ok(await page.evaluate(()=>window.demo.state.selected.length)>=highEvidence);await page.screenshot({path:`screenshots/${scene}_roi.png`,fullPage:true});
 const v=await page.locator('#viewer').boundingBox();await page.mouse.move(v.x+v.width*.5,v.y+v.height*.5);await page.mouse.down();await page.mouse.move(v.x+v.width*.7,v.y+v.height*.6,{steps:10});await page.mouse.up();await page.mouse.wheel(0,-150);await page.selectOption('#display','points');await slider('scale',2);await slider('opacity',.5);await page.selectOption('#display','ellipsoid');await page.check('#lock');await page.selectOption('#scene',scene==='mic'?'materials':'mic');await ready(scene==='mic'?'materials':'mic','F_001');assert.equal(await page.evaluate(()=>window.demo.state.selected.length),0);await page.uncheck('#lock');}
 assert.deepEqual(errors,[]);await writeFile('screenshots/browser_results.json',JSON.stringify({passed:true,frames:results,console_errors:errors},null,2));console.log(JSON.stringify({passed:true,frames:results,console_errors:errors},null,2));
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
